[theme]
base = "light"
primaryColor = "#1B98E0"
backgroundColor = "#E8F1F2"
secondaryBackgroundColor = "#006494"
textColor = "#13293D"
font = "sans serif"

[theme.dark]
base = "dark"
primaryColor = "#006494"
backgroundColor = "#13293D"
secondaryBackgroundColor = "#006494"
textColor = "#E8F1F2"
